version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/gui"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/gui/src-tauri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
